"""Opt-in, single-candidate revision contract; never a waiver or automatic retry."""

READER_REVISION_POLICY = "frozen-candidate-revision-v1"
REVISE_STAGE = "revise_report"
REVISED_REVIEW_STAGE = "verify_revised_report"
VERIFICATION_REPAIR_POLICY = "frozen-candidate-verification-v1"
FROZEN_REVIEW_STAGE = "verify_frozen_report"

VERIFICATION_REPAIR_REQUIREMENTS = (
    "This is a new attestation of the unchanged candidate, not permission to edit "
    "the reader or waive a finding. Reevaluate materiality and evidence independently. "
    "For audit_only_operational or audit_only_immaterial decisions, reader_excerpt "
    "must be an empty string and reader_excerpts must be empty. Do not attach contextual reader "
    "quotes to audit-only decisions. If a material caveat requires reader prose, use "
    "reader_covered with exact spans or unresolved; never force audit-only to satisfy "
    "the schema. Code-owned satisfied components are limited to their exact bound "
    "review scope; no financial, valuation, funding or user acceptance transfers."
)

REVISION_REQUIREMENTS = (
    "Revise the exact failed candidate using the frozen evidence and every remaining "
    "finding. This is one bounded revision, not permission to omit checks or invent facts. "
    "Distinguish repurchase authorization, evidence of execution, disclosed amounts and "
    "net dilution; do not convert missing amounts into absence of any execution. "
    "Keep the separate draft financial-case working-capital schedule distinct from "
    "reviewed narrow cash bridges and legacy proxies, including unresolved mixed rows. "
    "Preserve commitment dates/horizons, later obligations, guarantee default triggers "
    "and defined contractual coverage when supplied; contingency alone is not a complete "
    "description. Disclose material source-selection/truncation, retrieval completeness "
    "and table-extraction risks concisely. Distinguish supplied incentive mechanics and "
    "earned outcomes from unresolved target difficulty, realized pay sensitivity and "
    "investment returns. Never label supplied evidence absent merely because economic "
    "underwriting is incomplete. Procedural components explicitly classified by the "
    "code-owned applicability contract stay in the immutable audit; material economic "
    "and source-quality limits remain in the reader. Retain precise paragraph citations "
    "and calculation bindings, improve scenario interpretation and observable follow-up "
    "tests, and avoid implementation jargon and repeated caveats. Do not assert valuation, "
    "per-share value or company-wide funding approval. The new reader requires its own "
    "full factual and per-issue coverage verification; old attestations do not transfer."
)
